# Site settings
title: "Fitchburg State University: Game Design"
tagline: "A showcase of Game Design work from the students of Fitchburg State University"
url: "http://yourwebsite.com" # The base hostname & protocol for your site. Use it if you need absolute URLs
subdirectory: "" # this is placed before all relative urls, in case you want it to be on a subdirectory
permalink: /:title/

socialimg: "/assets/img/logo-color.png"

collections:
  games:
    output: true
    permalink: /games/:title/
  events:
    output: true
    permalink: /events/:title/
  communications-media:
    output: true
    permalink: /:title/
  film-video:
    output: true
    permalink: /film-video/:title/
  graphic-design:
    output: true
    permalink: /graphic-design/:title/
  photography:
    output: true
    permalink: /photography/:title/
  professional-communications:
    output: true
    permalink: /professional-communications/:title/
  theater:
    output: true
    permalink: /theater/:title/
  technical-theater:
    output: true
    permalink: /technical-theater/:title/

defaults:
  - scope:
      path: ""
      type: games
    values:
      layout: half-width
      main_image: placeholder.png
  - scope:
      path: ""
      type: events
    values:
      layout: full-width
  - scope:
      path: ""
      type: communications-media
    values:
      layout: gallery
  - scope:
      path: ""
      type: film-video
    values:
      layout: full-width
  - scope:
      path: ""
      type: graphic-design
    values:
      layout: full-width
  - scope:
      path: ""
      type: photography
    values:
      layout: full-width
  - scope:
      path: ""
      type: professional-communications
    values:
      layout: full-width
  - scope:
      path: ""
      type: theater
    values:
      layout: full-width
  - scope:
      path: ""
      type: technical-theater
    values:
      layout: full-width

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]