# Site settings
title: "Fitchburg State University: Game Design"
tagline: "A showcase of Game Design work from the students of Fitchburg State University"
url: "http://yourwebsite.com" # The base hostname & protocol for your site. Use it if you need absolute URLs
subdirectory: "" # this is placed before all relative urls, in case you want it to be on a subdirectory
permalink: /:title/

collections:
  games:
    output: true
    permalink: /games/:title/
  events:
    output: true
    permalink: /events/:title/

defaults:
  - scope:
      path: ""
      type: games
    values:
      layout: project
  - scope:
      path: ""
      type: events
    values:
      layout: event

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]